let seasonData = new Map();
let s1Logo = document.getElementById("s1");
let s2Logo = document.getElementById("s2");
let s3Logo = document.getElementById("s3");
let s4Logo = document.getElementById("s4");
let s5Logo = document.getElementById("s5");
let s6Logo = document.getElementById("s6");
let s7Logo = document.getElementById("s7");
let s8Logo = document.getElementById("s8");
let s9Logo = document.getElementById("s9");
let s10Logo = document.getElementById("s10");
let s11Logo = document.getElementById("s11");
let s12Logo = document.getElementById("s12");
let s13Logo = document.getElementById("s13");
let s14Logo = document.getElementById("s14");
let s15Logo = document.getElementById("s15");
let s16Logo = document.getElementById("s16");
let s17Logo = document.getElementById("s17");
let s18Logo = document.getElementById("s18");
let s19Logo = document.getElementById("s19");
let s20Logo = document.getElementById("s20");

seasonData.set(1, {
    seasonName: "Borneo",
    seasonWinner: "Richard Hatch",
    seasonLogo: s1Logo,
    castType: "newbie", // newbie, returnee, or mixed
    finalTribal: 2, // # of players in final tribal
    tier: 1,
    seasonCast: ["BB Anderson",
                "Colleen Haskel",
                "Dirk Been",
                "Gervase Peterson",
                "Greg Buis",
                "Gretchen Cordy",
                "Jenna Lewis",
                "Joel Klug",
                "Kelly Wiglesworth",
                "Ramona Gray",
                "Richard Hatch",
                "Rudy Boesch",
                "Sean Kenniff",
                "Sonja Christopher",
                "Stacey Stillman",
                "Susan Hawk"]
            });

seasonData.set(2, {
    seasonName: "Australian Outback",
    seasonWinner: "Tina Wesson",
    seasonLogo: s2Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 4,
    seasonCast: ["Alicia Calaway",
                "Amber Brkich",
                "Colby Donaldson",
                "Debb Eaton",
                "Elisabeth Filarski",
                "Jeff Varner",
                "Jerri Manthey",
                "Keith Famie",
                "Kel Gleason",
                "Kimmi Kappenberg",
                "Maralyn Hershey",
                "Michael Skupin",
                "Mitchell Olson",
                "Nick Brown",
                "Rodger Bingham",
                "Tina Wesson"]
            });

seasonData.set(3, {
    seasonName: "Africa",
    seasonWinner: "Ethan Zohn",
    seasonLogo: s3Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 2,
    seasonCast: ["Brandon Quinton",
                "Carl Bilancione",
                "Clarence Black",
                "Diane Ogden",
                "Ethan Zohn",
                "Frank Garrison",
                "Jessie Camacho",
                "Kelly Goldsmith",
                "Kim Johnson",
                "Kim Powers",
                "Lex van den Berghe",
                "Linda Spencer",
                "Lindsey Richter",
                "Silas Gaither",
                "Teresa Cooper",
                "Tom Buchanan"]
            });

seasonData.set(4, {
    seasonName: "Marquesas",
    seasonWinner: "Vecepia Towery",
    seasonLogo: s4Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 4,
    seasonCast: ["Gabriel Cade",
                "Gina Crews",
                "Hunter Ellis",
                "John Carroll",
                "Kathy Vavrick-O'Brien",
                "Neleh Dennis",
                "Paschal English",
                "Patricia Jackson",
                "Peter Harkey",
                "Rob Mariano",
                "Robert DeCanio",
                "Sarah Jones",
                "Sean Rector",
                "Tammy Leitner",
                "Vecepia Towery",
                "Zoe Zanidakis"]
            });

seasonData.set(5, {
    seasonName: "Thailand",
    seasonWinner: "Brian Heidik",
    seasonLogo: s5Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 4,
    seasonCast: ["Brian Heidik",
                "Clay Jordan",
                "Erin Collins",
                "Ghandia Johnson",
                "Helen Glover",
                "Jake Billingsley",
                "Jan Gentry",
                "Jed Hildebrand",
                "John Raymond",
                "Ken Stafford",
                "Penny Ramsey",
                "Robb Zbacnik",
                "Shii Ann Huang",
                "Stephanie Dill",
                "Tanya Vance",
                "Ted Rogers Jr"]
            });

seasonData.set(6, {
    seasonName: "Amazon",
    seasonWinner: "Jenna Morasca",
    seasonLogo: s6Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 1,
    seasonCast: ["Alex Bell",
                "Butch Lockley",
                "Christy Smith",
                "Daniel Lue",
                "Dave Johnson",
                "Deena Bennett",
                "Heidi Strobel",
                "Janet Koth",
                "Jeanne Hebert",
                "Jenna Morasca",
                "JoAnna Ward",
                "Matthew von Ertfelda",
                "Rob Cesternino",
                "Roger Sexton",
                "Ryan Aiken",
                "Shawna Mitchell"]
            });

seasonData.set(7, {
    seasonName: "Pearl Islands",
    seasonWinner: "Sandra Diaz-Twine",
    seasonLogo: s7Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 1,
    seasonCast: ["Andrew Savage",
                "Burton Roberts",
                "Christa Hastie",
                "Darrah Johnson",
                "Jon Dalton",
                "Lillian Morris",
                "Michelle Tesauro",
                "Nicole Delma",
                "Osten Taylor",
                "Rupert Boneham",
                "Ryan Opray",
                "Ryan Shoulders",
                "Sandra Diaz-Twine",
                "Shawn Cohen",
                "Tijuana Bradley",
                "Trish Dunn"]
            });

seasonData.set(8, {
    seasonName: "All-Stars",
    seasonWinner: "Amber Brkich",
    seasonLogo: s8Logo,
    castType: "returnee",
    finalTribal: 2,
    tier: 3,
    seasonCast: ["Alicia Calaway",
                "Amber Brkich",
                "Colby Donaldson",
                "Ethan Zohn",
                "Jenna Lewis",
                "Jenna Morasca",
                "Jerri Manthey",
                "Kathy Vavrick-O'Brien",
                "Lex van den Berghe",
                "Richard Hatch",
                "Rob Cesternino",
                "Rob Mariano",
                "Rudy Boesch",
                "Rupert Boneham",
                "Shii Ann Huang",
                "Susan Hawk",
                "Tina Wesson",
                "Tom Buchanan"]
            });

seasonData.set(9, {
    seasonName: "Vanuatu",
    seasonWinner: "Chris Daugherty",
    seasonLogo: s9Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 3,
    seasonCast: ["Ami Cusack",
                "Brady Finta",
                "Brook Geraghty",
                "Chad Crittenden",
                "Chris Daugherty",
                "Dolly Neely",
                "Eliza Orlins",
                "John Kenney",
                "John Palyok",
                "Julie Berry",
                "Lea Masters",
                "Leann Slaby",
                "Lisa Keiffer",
                "Mia Galeotalanza",
                "Rory Freeman",
                "Scout Cloud Lee",
                "Travis Sampson",
                "Twila Tanner"]
            });

seasonData.set(10, {
    seasonName: "Palua",
    seasonWinner: "Tom Westman",
    seasonLogo: s10Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 2,
    seasonCast: ['Angie Jakusz',
                'Ashlee Ashby',
                'Bobby Jon Drinkard',
                'Caryn Groedel',
                'Coby Archa',
                'Gregg Carey',
                'Ian Rosenberger',
                'Ibrehem Rahman',
                'James Miller',
                'Janu Tornell',
                'Jeff Wilson',
                'Jenn Lyon',
                'Jolanda Jones',
                'Jonathan Libby',
                'Katie Gallagher',
                'Kim Mullen',
                'Stephenie LaGrossa',
                'Tom Westman',
                'Wanda Shirk',
                'Willard Smith']
            });

seasonData.set(11, {
    seasonName: "Guatemala",
    seasonWinner: "Danni Boatwright",
    seasonLogo: s11Logo,
    castType: "mixed",
    finalTribal: 2,
    tier: 3,
    seasonCast: ["Amy O'Hara",
                'Blake Towsley',
                'Bobby Jon Drinkard',
                'Brandon Bellinger',
                'Brian Corridan',
                'Brianna Varela',
                'Brooke Struck',
                'Cindy Hall',
                'Danni Boatwright',
                'Gary Hogeboom',
                'Jamie Newton',
                'Jim Lynch',
                'Judd Sergeant',
                'Lydia Morales',
                'Margaret Bobonich',
                'Morgan McDevitt',
                'Rafe Judkins',
                'Stephenie LaGrossa']
            });

seasonData.set(12, {
    seasonName: "Panama",
    seasonWinner: "Aras Baskauskas",
    seasonLogo: s12Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 3,
    seasonCast: ['Aras Baskauskas',
                'Austin Carty',
                'Bobby Mason',
                'Bruce Kanegai',
                'Cirie Fields',
                'Courtney Marit',
                'Dan Barry',
                'Danielle DiLorenzo',
                'Melinda Hyder',
                'Misty Giles',
                'Nick Stanbury',
                'Ruth Marie Milliman',
                'Sally Schumann',
                'Shane Powers',
                'Terry Deitz',
                'Tina Scheer']
            });

seasonData.set(13, {
    seasonName: "Cook Islands",
    seasonWinner: "Yul Kwon",
    seasonLogo: s13Logo,
    castType: "newbie",
    finalTribal: 3,
    tier: 2,
    seasonCast: ['Adam Gentry',
                'Becky Lee',
                'Billy Garcia',
                'Brad Virata',
                'Candice Woodcock',
                'Cao Boi Bui',
                'Cecilia Mansilla',
                'Cristina Coria',
                'J.P. Calderon',
                'Jenny Guzon-Bae',
                'Jessica Smith',
                'Jonathan Penner',
                'Nate Gonzalez',
                'Ozzy Lusth',
                'Parvati Shallow',
                'Rebecca Borman',
                'Sekou Bunch',
                'Stephannie Favor',
                'Sundra Oakley',
                'Yul Kwon']
            });

seasonData.set(14, {
    seasonName: "Fiji",
    seasonWinner: "Earl Cole",
    seasonLogo: s14Logo,
    castType: "newbie",
    finalTribal: 3,
    tier: 4,
    seasonCast: ['Alex Angarita',
                'Anthony Robinson',
                'Boo Bernis',
                'Cassandra Franklin',
                'Dreamz Herd',
                'Earl Cole',
                'Edgardo Rivera',
                'Erica Durousseau',
                'Gary Stritesky',
                'Jessica deBen',
                'Liliana Gomez',
                'Lisi Linares',
                'Michelle Yi',
                'Mookie Lee',
                'Rita Verreos',
                'Rocky Reid',
                'Stacy Kimball',
                'Sylvia Kwan',
                'Yau-Man Chan']
            });

seasonData.set(15, {
    seasonName: "China",
    seasonWinner: "Todd Herzog",
    seasonLogo: s15Logo,
    castType: "newbie",
    finalTribal: 3,
    tier: 2,
    seasonCast: ['Aaron Reisberger',
                'Amanda Kimmel',
                'Ashley Massaro',
                'Chicken Morris',
                'Courtney Yates',
                'Dave Cruser',
                'Denise Martin',
                'Erik Huffman',
                'Frosti Zernow',
                'Jaime Dugan',
                'James Clement',
                'Jean-Robert Bellande',
                'Leslie Nease',
                'Peih-Gee Law',
                'Sherea Lloyd',
                'Todd Herzog']
            });

seasonData.set(16, {
    seasonName: "Micronesia",
    seasonWinner: "Parvati Shallow",
    seasonLogo: s16Logo,
    castType: "mixed",
    finalTribal: 2,
    tier: 2,
    seasonCast: ['Alexis Jones',
                'Amanda Kimmel',
                'Ami Cusack',
                'Chet Welch',
                'Cirie Fields',
                'Eliza Orlins',
                'Erik Reichenbach',
                'James Clement',
                'Jason Siska',
                'Joel Anderson',
                'Jon Dalton',
                'Jonathan Penner',
                'Kathy Sleckman',
                'Mary Sartain',
                'Mikey Bortone',
                'Natalie Bolton',
                'Ozzy Lusth',
                'Parvati Shallow',
                'Tracy Hughes-Wolf',
                'Yau-Man Chan']
            });

seasonData.set(17, {
    seasonName: "Gabon",
    seasonWinner: "Bob Crowley",
    seasonLogo: s17Logo,
    castType: "newbie",
    finalTribal: 3,
    tier: 4,
    seasonCast: ['Ace Gordon',
                'Bob Crowley',
                'Charlie Herschel',
                'Corinne Kaplan',
                'Crystal Cox',
                'Dan Kay',
                'GC Brown',
                'Gillian Larson',
                'Jacquie Berg',
                'Kelly Czarnecki',
                'Ken Hoang',
                'Marcus Lehman',
                'Matty Whitmore',
                'Michelle Chase',
                'Paloma Soto-Castillo',
                'Randy Bailey',
                'Sugar Kiper',
                'Susie Smith']
            });

seasonData.set(18, {
    seasonName: "Tocantins",
    seasonWinner: "J.T. Thomas",
    seasonLogo: s18Logo,
    castType: "newbie",
    finalTribal: 2,
    tier: 1,
    seasonCast: ['Brendan Synnott',
                'Candace Smith',
                'Carolina Eastwood',
                'Coach Wade',
                'Debbie Beebe',
                'Erinn Lobdell',
                'J.T. Thomas',
                'Jerry Sims',
                'Joe Dowdle',
                'Sandy Burgin',
                'Sierra Reed',
                'Spencer Duhm',
                'Stephen Fishbach',
                'Sydney Wheeler',
                'Taj Johnson-George',
                'Tyson Apostol']
            });

seasonData.set(19, {
    seasonName: "Samoa",
    seasonWinner: "Natalie White",
    seasonLogo: s19Logo,
    castType: "newbie",
    finalTribal: 3,
    tier: 3,
    seasonCast: ['Ashley Trainer',
                'Ben Browning',
                'Betsy Bolan',
                'Brett Clouser',
                'Dave Ball',
                'Erik Cardona',
                'Jaison Robinson',
                'John Fincher',
                'Kelly Sharbaugh',
                'Laura Morett',
                'Liz Kim',
                'Marisa Calihan',
                'Mick Trimming',
                'Mike Borassi',
                'Monica Padilla',
                'Natalie White',
                'Russell Hantz',
                'Russell Swan',
                'Shambo Waters',
                'Yasmin Giles']
            });

seasonData.set(20, {
    seasonName: "Heroes vs Villians",
    seasonWinner: "Sandra Diaz-Twine",
    seasonLogo: s20Logo,
    castType: "returnee",
    finalTribal: 3,
    tier: 1,
    seasonCast: ['Amanda Kimmel',
                'Candice Woodcock',
                'Cirie Fields',
                'Coach Wade',
                'Colby Donaldson',
                'Courtney Yates',
                'Danielle DiLorenzo',
                'J.T. Thomas',
                'James Clement',
                'Jerri Manthey',
                'Parvati Shallow',
                'Randy Bailey',
                'Rob Mariano',
                'Rupert Boneham',
                'Russell Hantz',
                'Sandra Diaz-Twine',
                'Stephenie LaGrossa',
                'Sugar Kiper',
                'Tom Westman',
                'Tyson Apostol']
            });
